<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitReportReporter -->
<testsuite hostname="DUS92VDC2D15008" name="com.siebel.mcrmapp.testsuite.InboundContactManagementTest" tests="1" failures="0" timestamp="26 Oct 2015 07:44:48 GMT" time="94.822" errors="1">
  <testcase name="checkSRCreationMandatoryErroMessage" time="94.822" classname="com.siebel.mcrmapp.testsuite.InboundContactManagementTest">
    <error type="java.lang.AssertionError" message="Test Case Fails as the Outgoing Channel field in the created SR is not displayed as Auto Populated expected [true] but found [false]">
      <![CDATA[java.lang.AssertionError: Test Case Fails as the Outgoing Channel field in the created SR is not displayed as Auto Populated expected [true] but found [false]
	at org.testng.Assert.fail(Assert.java:94)
	at org.testng.Assert.failNotEquals(Assert.java:494)
	at org.testng.Assert.assertTrue(Assert.java:42)
	at com.siebel.mcrm.main.classes.InboundContactManagment.checkSRCreationMandatoryErroMessage(InboundContactManagment.java:847)
	at com.siebel.mcrmapp.testsuite.InboundContactManagementTest.checkSRCreationMandatoryErroMessage(InboundContactManagementTest.java:200)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:84)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:714)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:901)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1231)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:127)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:111)
	at org.testng.TestRunner.privateRun(TestRunner.java:767)
	at org.testng.TestRunner.run(TestRunner.java:617)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:348)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:343)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:305)
	at org.testng.SuiteRunner.run(SuiteRunner.java:254)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1224)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1149)
	at org.testng.TestNG.run(TestNG.java:1057)
	at org.testng.remote.RemoteTestNG.run(RemoteTestNG.java:111)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:204)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:175)
]]>
    </error>
  </testcase> <!-- checkSRCreationMandatoryErroMessage -->
</testsuite> <!-- com.siebel.mcrmapp.testsuite.InboundContactManagementTest -->
